title: "Alexis Chollet"
description: ".Net Software Senior Engineer"
url: "https://achollet.github.io/"
baseurl: ""

author:
  name: "Alexis Chollet"
  email: "alexis.chollet@gmail.com"
  github: "https://github.com/achollet"
  linkedin: "https://linkedin.com/in/drcholletalexis"
  about: "Machine Learning Engineer with a passion for applied AI and distributed systems. I work on problems ranging from NLP to computer vision, with a focus on scalability and model robustness in production environments."

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
